name: topbar_test
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.4.3
  hive_ce: ^2.11.0-pre.5
  hive_ce_flutter: ^2.3.0-pre.1

dev_dependencies:
  rexios_lints: ^10.1.0

flutter:
  uses-material-design: true
